---
required_approvals:
  default: 1
  gnocchixyz/gnocchi@master: 2
  gnocchixyz/python-gnocchiclient@master: 2

branch_protection_enforce_admins:
  default: false
  gnocchixyz/-: true
  gnocchixyz/grafana-gnocchi-datasource: false
  gnocchixyz/gnocchi-docker: false

branch_protection_contexts:
  default:
    - continuous-integration/travis-ci
  sileht/cotyledon:
    - continuous-integration/tea
    - continuous-integration/travis-ci
