---
required_approvals:
  default: 1
  -@master: 2
  sileht/pastamaker: 1
  gnocchixyz/gnocchi-docker: 1
  gnocchixyz/tools-tester: 1
  gnocchixyz/tools-tester@master: 1
  gnocchixyz/grafana-gnocchi-datasource: 1

branch_protection_enforce_admins:
  default: true
  sileht/pastamaker: false
  gnocchixyz/grafana-gnocchi-datasource: false
